### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#11]
Thanks for such prompt attention to the recent issues from readxl.

We are pushing to a release, in order to get a readxl version on CRAN that includes the fixes for the CVEs.

readxl is in a functional state as of c7e5e49518027c2a8bf65c933b1a7f8804a8f7fb, i.e. all tests pass.

However, we have to do a fair amount of manual patching to make embedded libxls acceptable to CRAN 😔, i.e. to generate no NOTEs with their compiler settings on all tested platforms.

I now see many commits have been made since then and I want to take advantage of the most current libxls when I submit to CRAN. But I also want to minimize the manual application of my "CRAN fixups".

Can you give me a sense of your near-term plans? Do you foresee sporadic development for a while or are you pushing towards a distinct release too? It helps me plan my work.

Thanks in advance.

**Comment by evanmiller** [comment]
Hi @jennybc,

There are no additional features or API changes planned for the next release. There will likely be a few more code commits, as the current test suite indicates that memory leaks are present somewhere in the library, but an official release / transition is likely a few months away.

What are the manual fixups? I'd like to accommodate as many client applications / build environments as I can.

**Comment by jennybc** [comment]
> What are the manual fixups?

Oh wow, I'd love it if we could collaborate to eliminate some of these! I will come back here with an organized summary of what I do every time I pull upstream changes in.

**Comment by jennybc** [comment]
The new release of readxl (version 1.1.0) is on CRAN now, although none of the binaries have been updated yet:

https://cran.r-project.org/package=readxl

I will continue to bring up our manual patches when I think a change would be desirable in libxls or when I hope you'll accept our change.
