### ISSUE TITLE
Segfault reading specific xls

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#13]
Via readxl. However I get a segfault using xls2csv alone. I built from 172a0ac0c47c0736ed1c1188a7ed79288860f004.

```
jenny@2015-mbp libxls-evanmiller-github $ ./xls2csv ~/Downloads/2017q1table1a.xls
FILE: /Users/jenny/Downloads/2017q1table1a.xls
Segmentation fault: 11
```

The xls file comes from here:
https://www.transportation.gov/office-policy/aviation-policy/table-1a-domestic-airline-airfare-report-–-first-quarter-2017-excel

https://github.com/tidyverse/readxl/issues/391

**Comment by jennybc** [comment]
I've rebuilt xls2csv and now I get this (no segfault, but no output or additional error message):

```
jenny@2015-mbp libxls-evanmiller-github $ ./xls2csv ~/Downloads/2017q1table1a.xls
FILE: /Users/jenny/Downloads/2017q1table1a.xls
```

In a branch of readxl that includes this change, I no longer default but I don't read anything either:

``` r
> read_excel("~/Downloads/2017q1table1a.xls")
# A tibble: 0 x 0
```

**Comment by evanmiller** [comment]
Hi, for some reason this file is being parsed as empty. I'm not sure what's going on. If you encounter these symptoms with other files, feel free to open a new issue about it.

(My priority at the moment is fixing any segfaults, regressions, and incorrect data.)

**Comment by jennybc** [comment]
> My priority at the moment is fixing any segfaults, regressions, and incorrect data

Good to know. If I look into this one, I will let you know. I am also just trying to get a release out with the security patches. No new features.
