### ISSUE TITLE
"Unable to allocate memory"

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#22]
Via readxl, I have a file that generates this error when I attempt to read with xls2csv:

```
jenny@2015-mbp libxls-evanmiller-github $ ./xls2csv ~/rrr/readxl/investigations/pop-sexe-age-quinquennal6814.xlsFILE: /Users/jenny/rrr/readxl/investigations/pop-sexe-age-quinquennal6814.xls
Error reading XLS file: Unable to allocate memory
```

See https://github.com/tidyverse/readxl/issues/478

Is this something you care to pursue? That is, is the error message just a sentinel and we're bumping against a semi-arbitrary limit you might raise? The OP reports being able to read this xls file with an earlier version of readxl (haven't verified, but have no reason to doubt) and same file, saved as xlsx, is also readable.

**Comment by evanmiller** [comment]
Thanks. These errors are designed to prevent DoS-style attacks where malformed input may trigger massive memory allocations. I'll investigate.

**Comment by evanmiller** [comment]
I've bumped the arbitrary limit on the number of shared strings from 2^20 (1 million) to 2^24 (16 million). That should fix the specific file you referenced.

I am happy to look into other issues raised by readxl users. It would help me somewhat if the submitted read failures were organized by error message; currently the issues in the readxl repo have rather generic titles ("Problem loading xls file", "Failed to open specific .xls file", etc).

**Comment by jennybc** [comment]
>  It would help me somewhat if the submitted read failures were organized by error message

Roger. FWIW I think alot of the current failures are not producing an error, but are producing a result with zero rows.
