### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#25]
Hi @evanmiller,

Exciting to see activity here!

For external reasons, I have to do a minor readxl release very soon. I always update the embedded libxls when I do this.

Do you predict an official libxls release in the next week and I should try to plan around that?

Or should I proceed on my own schedule? If I do not / cannot wait for an official libxls release, is there a specific SHA or tag you regard as more stable and release-ish?

**Comment by evanmiller** [comment]
The current b20521f964d0c22b45db0b8c97a9d777bccd0f7f should be okay for inclusion. I need to coordinate with David as far as an official release goes.

**Comment by jennybc** [comment]
OK thanks for the info.
