### ISSUE TITLE
xls file throws no error, but no cell data retrieved ("Arrivals sheet")

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#29]
We've discussed this one before and you applied a fix that went from "segfault" to "no segfault but no data returned". At that time, you expressed (somewhere? email?) that you were focused on preventing segfaults.

Previous issue here: https://github.com/evanmiller/libxls/issues/20

Tracking in readxl here: https://github.com/tidyverse/readxl/issues/471

I bring it up again in case it's a better time to run this one down for real.

This is an xls that libxls and readxl *used* to be able to read (readxl v1.0.0), so **it's a regression**.

The xls is here:

http://homepage.stat.uiowa.edu/~luke/data/Arrivals-2017-01-06.xls

With the standalone xls2csv tool as of libxls b6192a3eb4f5ba99435db259ca1fb442b1e8cba7, I see:

```
jenny@2015-mbp libxls-evanmiller-github $ ./xls2csv ~/rrr/readxl/investigations/Arrivals-2017-01-06.xls
FILE: /Users/jenny/rrr/readxl/investigations/Arrivals-2017-01-06.xls
```

and a whole whack of newlines. The verbose mode with `-v` reveals the file is being parsed.

**Comment by evanmiller** [comment]
Should be fixed now. Thanks!

**Comment by jennybc** [comment]
Yes, fixed. Great!
