### ISSUE TITLE
workflow hiccup for people who git pull

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#32]
Something that's changed recently means that I have to do `autoreconf -f -i` every time I pull from upstream and want to rebuild the xls2csv tool.

Is there anything that is easy to change re: the setup that would make this problem go away? Or do I just need to remember to do this now? If that's the case, it should probably be added to the README.

```
jenny@2015-mbp libxls-evanmiller-github $ autoreconf -f -i
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
glibtoolize: and rerunning glibtoolize and aclocal.
glibtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:25: installing './compile'
configure.ac:22: installing './missing'
Makefile.am: installing './depcomp'
```

**Comment by evanmiller** [comment]
What was the previous behavior? I have been tinkering with the build scripts lately, but I am far from an autotools expert.

On my own machine, a simple "make" will re-run autoconf if the input scripts have changed, then re-run configure. So "make clean" followed by "make" does a full regen + rebuild.

**Comment by jennybc** [comment]
It used to "just work". It's been so long since I've done this drill (versus `brew install thingy`) that I have *not* been doing `make clean` before starting afresh after a pull. I just forgot. But I'll try `make clean` next time and report back.

**Comment by jennybc** [comment]
This SO post suggests it is not unusual to see this phenomenon with this particular combination of tooling (this is where I found the `autoreconf -f -i` tip):

https://stackoverflow.com/questions/33278928/how-to-overcome-aclocal-1-15-is-missing-on-your-system-warning-when-compilin

**Comment by evanmiller** [comment]
Well, I've pushed changes after running autoreconf locally. Not sure if that will fix anything, but the scripts have newer copyright notices, so it feels like progress.
