### ISSUE TITLE
Guidance on packaging?

### ISSUE THREAD

**Issue by sjmulder** [evanmiller/libxls#38]
Hi, I'm creating a [pkgsrc](http://pkgsrc.org/) package for libxls. There are a few options wrt. the CVE situation:

1. Release 1.4.0 as-is and mark it as vulnerable (users will have to override a flag to install)
2. Release 1.4.0 with cherry picked patches for the CVE and memory issues
3. Wait for 1.5.0

I'm a bit wary of no. 2 so I suppose it's mostly about the timeframe of a 1.5.0 release. What would you recommend?

**Comment by evanmiller** [comment]
I'm hoping to release a 1.5 in the coming weeks. Pretty much everything is in place, just waiting on some final blessings from the previous maintainers.

**Comment by sjmulder** [comment]
Cool, thanks for all the work you’re doing here!
